name = "Hugo Future Imperfect"
license = "MIT"
licenselink = "https://github.com/jpescador/hugo-future-imperfect/blob/master/LICENSE.md"
description = "HTML5 UP theme, Future Imperfect, with some extra goodies."
homepage = "https://github.com/jpescador/hugo-future-imperfect"
tags = ["Blog", "Responsive", "Portfolio", "Disqus", "Syntax Highlighting",
        "Company", "Font Awesome", "Projects", "Contact Form", "Highlight.js",
        "Gallery", "Multilingual", "Product", "Fancybox", "Academicons", "Academic",
        "Google Analytics", "Twitter Cards", "Open Graph", "Google News",
        "Jquery", "Skel", "Staticman", "Netlify"]
features = ["Highlight.js v9.1", "Font Awesome v4.7", "Fancybox v3.1",
            "Academicons v1.8", "Google Analytics", "Disqus", "Twitter Cards",
            "Open Graph", "Google News", "Jquery v3.2", "Skel v3.0", "Staticman",
            "Netlify"]
min_version = 0.15

[author]
  name = "Julio Pescador"
  homepage = "https://jpescador.com"

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "http://html5up.net/future-imperfect"
  repo = ""
